[package]
name = 'bash-core'
slug = 'core'
version = '0.1.1'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'Core lightweight functions that any Bash programmer will love'

[run]
dependencies = ['https://github.com/hyperupcall/bats-all.git@v4.1.0']
sourceDirs = ['pkg/lib/public', 'pkg/lib/util']
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
