name: 'Build and Deploy Site'
on:
  push:
    branches-ignore: ['*-no-ci']
  pull_request:
    branches-ignore: ['*-no-ci']

permissions:
  contents: 'read'
  pages: 'write'
  id-token: 'write'

defaults:
  run:
    shell: 'bash'

  # TODO
  # concurrency:
  #   group: '${{ github.ref }}'
  #   cancel-in-progress: true

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - run: |
          cat > mkdocs.yml <<EOF
          site_name: '${{ github.event.repository.name }}'
          site_url: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}'
          repo_url: '${{ github.event.repository.url }}'
          # edit_uri: `edit/${settings.remoteBranchNameSource}/${settings.docsInputDir}/`
          # site_description: "" // TODO
          site_author: Edwin Kofler
          copyright: '© Edwin Kofler'
          # remote_branch: settings.remoteBranchName
          # remote_name: settings.remoteName
          docs_dir: './docs'
          site_dir: './output'
          EOF
          pipx run mkdocs build -f './mkdocs.yml'
      - uses: 'actions/upload-pages-artifact@v2'
        with:
          path: './output'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
